name: Pylint & Security Scan

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"] 

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # On ajoute 'bandit' ici pour qu'il soit reconnu plus tard
        pip install pylint flask pytest bandit 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Analysing the code with pylint
      run: |
        pylint app.py tests/test_app.py

    - name: Security scan with Bandit
      run: |
        bandit -r . -v